### ISSUE TITLE
Athena JDBC's MD5 checksum doesn't match with the one by provided by AWS

### ISSUE THREAD

**Issue by Barbayar** [getredash/redash-amazon-athena-proxy#3]
I downloaded Athena JDBC driver from s3://athena-downloads/drivers/AthenaJDBC41-1.0.1.jar, and its MD5 was `9cf549c2f690d8f5085483805d8e8b75`.

Where `athena-1.0.jar` in this repo came from? I tried to download `AthenaJDBC41-1.0.0.jar` not `AthenaJDBC41-1.0.0.jar`, to check if `redash-amazon-athena-proxy` is using `1.0.0`, but couldn't find `1.0.0`

**Comment by arikfr** [comment]
athena-1.0.jar is the previous version Amazon were distributing.
