### ISSUE TITLE
update AthenaJDBC

### ISSUE THREAD

**Issue by shogomuranushi** [getredash/redash-amazon-athena-proxy#4]
Hello.
Is it possible to change Athena JDBC from 1.0 to 1.1?
`AthenaJDBC41-1.1.0.jar` is released.

**Comment by arikfr** [comment]
This proxy is now deprecate in favor of the direct connector we have in the [new release (v2.0.0)](https://github.com/getredash/redash/releases/tag/v2.0.0). 

I won't be doing any updates to it, but you're welcome to submit a pull request if you have any future use for the proxy.
